// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CastToDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['CastToDevice'](arg1, arg2, arg3);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DiscoverDevices() {
  return window['go']['main']['App']['DiscoverDevices']();
}

export function FindSubtitleFile(arg1) {
  return window['go']['main']['App']['FindSubtitleFile'](arg1);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetMediaFiles(arg1) {
  return window['go']['main']['App']['GetMediaFiles'](arg1);
}

export function GetMediaURL(arg1) {
  return window['go']['main']['App']['GetMediaURL'](arg1);
}

export function GetPlaybackState() {
  return window['go']['main']['App']['GetPlaybackState']();
}

export function GetSubtitleTracks(arg1) {
  return window['go']['main']['App']['GetSubtitleTracks'](arg1);
}

export function GetSubtitleURL(arg1) {
  return window['go']['main']['App']['GetSubtitleURL'](arg1);
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function LogWarn(arg1) {
  return window['go']['main']['App']['LogWarn'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenSubtitleDialog() {
  return window['go']['main']['App']['OpenSubtitleDialog']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function SeekTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['SeekTo'](arg1, arg2, arg3);
}

export function StopPlayback() {
  return window['go']['main']['App']['StopPlayback']();
}

export function Unpause() {
  return window['go']['main']['App']['Unpause']();
}

export function UpdatePlaybackState() {
  return window['go']['main']['App']['UpdatePlaybackState']();
}

export function UpdateSubtitleSettings(arg1) {
  return window['go']['main']['App']['UpdateSubtitleSettings'](arg1);
}
