// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {options} from '../models';
import {main} from '../models';
import {folders} from '../models';
import {remote} from '../models';
import {ffmpeg} from '../models';

export function ApplyRemoteAPISettings(arg1:boolean,arg2:number,arg3:string):Promise<void>;

export function CancelSeasonTranslation():Promise<void>;

export function CancelTranslation():Promise<void>;

export function CastToDevice(arg1:string,arg2:string,arg3:options.CastOptions):Promise<main.PlaybackState>;

export function ClearCache():Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteAllVideoCache():Promise<void>;

export function DeleteTranscodedCache():Promise<void>;

export function DiscoverCastInstances():Promise<Array<main.CastInstance>>;

export function DiscoverDevices():Promise<Array<main.Device>>;

export function Export():Promise<main.AppExports>;

export function ExportEmbeddedSubtitles(arg1:string):Promise<void>;

export function GenerateTranslationPrompt(arg1:string,arg2:string):Promise<string>;

export function GetCacheStats():Promise<folders.CacheStats>;

export function GetDownloadStatus(arg1:string,arg2:string,arg3:number):Promise<remote.DownloadStatusQeuryResponse>;

export function GetFFmpegInfo(arg1:boolean):Promise<ffmpeg.FFmpegInfo>;

export function GetHistory():Promise<Array<main.HistoryItem>>;

export function GetMediaFiles(arg1:string):Promise<Array<string>>;

export function GetRemoteAPIAddress():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetTrackDisplayInfo(arg1:string):Promise<main.TrackDisplayInfo>;

export function IdentifyLibrary(arg1:main.LibraryScanResult):Promise<main.LibraryScanResult>;

export function ListLibraryItems():Promise<Array<main.LibraryItem>>;

export function ListModels(arg1:string):Promise<Array<string>>;

export function LogError(arg1:string,arg2:Array<any>):Promise<void>;

export function LogInfo(arg1:string,arg2:Array<any>):Promise<void>;

export function LogWarn(arg1:string,arg2:Array<any>):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function OpenLibraryFolderDialog():Promise<string>;

export function OpenMediaFolder(arg1:string):Promise<void>;

export function OrganizeLibrary(arg1:Array<main.OrganizeMove>):Promise<void>;

export function Pause():Promise<void>;

export function PreviewOrganize(arg1:main.LibraryScanResult):Promise<Array<main.OrganizeMove>>;

export function ProcessPastedTranslation(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function RemoteAddTorrent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoteControl(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.PlaybackState>;

export function RemoteDevices(arg1:string,arg2:string):Promise<Array<main.RemoteDevice>>;

export function RemoteIdentify(arg1:string,arg2:string,arg3:main.LibraryScanResult):Promise<main.LibraryScanResult>;

export function RemoteLibrary(arg1:string,arg2:string):Promise<Array<main.LibraryItem>>;

export function RemoteLibraryTree(arg1:string,arg2:string):Promise<main.LibraryScanResult>;

export function RemoteOrganizeExecute(arg1:string,arg2:string,arg3:Array<main.OrganizeMove>):Promise<void>;

export function RemoteOrganizePreview(arg1:string,arg2:string,arg3:main.LibraryScanResult):Promise<Array<main.OrganizeMove>>;

export function RemotePing(arg1:string,arg2:string):Promise<boolean>;

export function RemotePlay(arg1:string,arg2:string,arg3:string,arg4:string,arg5:main.RemotePlayOptions):Promise<main.PlaybackState>;

export function RemoteSeasonCancel(arg1:string,arg2:string):Promise<void>;

export function RemoteSeasonStatus(arg1:string,arg2:string):Promise<main.SeasonTranslateProgress>;

export function RemoteState(arg1:string,arg2:string):Promise<main.PlaybackState>;

export function RemoteTorrents(arg1:string,arg2:string):Promise<Array<main.TorrentStatus>>;

export function RemoteTrackInfo(arg1:string,arg2:string,arg3:string):Promise<main.TrackDisplayInfo>;

export function RemoteTranslateFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RemoteTranslateSeason(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<void>;

export function RemoteTranslateStatus(arg1:string,arg2:string):Promise<main.translateStatus>;

export function RemoteUpdateSubtitle(arg1:string,arg2:string,arg3:options.SubtitleCastOptions):Promise<void>;

export function RemoveFromHistory(arg1:string):Promise<void>;

export function ResetSettings():Promise<main.Settings>;

export function ScanLibrary(arg1:string):Promise<main.LibraryScanResult>;

export function SeekTo(arg1:number):Promise<void>;

export function SetMuted(arg1:boolean):Promise<void>;

export function SetSubtitleSize(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StartDownload(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StopDownload(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StopPlayback():Promise<void>;

export function TranslateExportedSubtitles(arg1:string,arg2:string):Promise<void>;

export function TranslateSeason(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function Unpause():Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;

export function UpdateSubtitleSettings(arg1:options.SubtitleCastOptions):Promise<void>;
