// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CastToDevice(arg1:string,arg2:string):Promise<void>;

export function DiscoverDevices():Promise<Array<main.Device>>;

export function GetLocalIP():Promise<string>;

export function GetMediaFiles(arg1:string):Promise<Array<string>>;

export function GetMediaURL(arg1:string):Promise<string>;

export function LogError(arg1:string,arg2:Array<any>):Promise<void>;

export function LogInfo(arg1:string,arg2:Array<any>):Promise<void>;

export function LogWarn(arg1:string,arg2:Array<any>):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;
