// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {mediainfo} from '../models';

export function CastToDevice(arg1:string,arg2:string,arg3:main.CastOptions):Promise<main.PlaybackState>;

export function ClearCache():Promise<void>;

export function DiscoverDevices():Promise<Array<main.Device>>;

export function FindSubtitleFile(arg1:string):Promise<string>;

export function GetMediaFiles(arg1:string):Promise<Array<string>>;

export function GetMediaTrackInfo(arg1:string):Promise<mediainfo.MediaTrackInfo>;

export function GetMediaURL(arg1:string):Promise<string>;

export function GetRemoteTrackInfo(arg1:string):Promise<mediainfo.MediaTrackInfo>;

export function GetSubtitleTracks(arg1:string):Promise<Array<mediainfo.SubtitleTrack>>;

export function GetSubtitleURL(arg1:string):Promise<string>;

export function LogError(arg1:string):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function LogWarn(arg1:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function OpenSubtitleDialog():Promise<string>;

export function Pause():Promise<void>;

export function SeekTo(arg1:number):Promise<void>;

export function StopPlayback():Promise<void>;

export function Unpause():Promise<void>;

export function UpdateSubtitleSettings(arg1:main.CastOptions):Promise<void>;
