// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CastToDevice(arg1, arg2) {
  return window['go']['main']['App']['CastToDevice'](arg1, arg2);
}

export function DiscoverDevices() {
  return window['go']['main']['App']['DiscoverDevices']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetMediaFiles(arg1) {
  return window['go']['main']['App']['GetMediaFiles'](arg1);
}

export function GetMediaURL(arg1) {
  return window['go']['main']['App']['GetMediaURL'](arg1);
}

export function LogError(arg1, arg2) {
  return window['go']['main']['App']['LogError'](arg1, arg2);
}

export function LogInfo(arg1, arg2) {
  return window['go']['main']['App']['LogInfo'](arg1, arg2);
}

export function LogWarn(arg1, arg2) {
  return window['go']['main']['App']['LogWarn'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
